### ISSUE TITLE
win10+eclipse+gradle+jpf-core

### ISSUE THREAD

**Issue by Marvinmw** [javapathfinder/jpf-core#185] opened 2019-04-29 13:56 UTC
When I built JPF-core in Eclipse on Win10. I get the error,
AILURE: Build failed with an exception.

* Where:
Script 'C:\Users\wei.ma\SEJPF\jpf-core\gradle\build-resources.gradle' line: 32

* What went wrong:
Execution failed for task ':generateBuildInfo'.
> java.io.FileNotFoundException: build.properties (Access is denied)

**Comment by ranjsa** [comment] 2020-03-10 11:15
@cyrille-artho 

According to the issue description the build is failing at **jpf-core\gradle\build-resources.gradle' line: 32** with error **java.io.FileNotFoundException: build.properties (Access is denied)**
which is this
![issue#185](https://user-images.githubusercontent.com/43692789/76306641-49042100-62ed-11ea-971a-5696c45631f3.PNG)

At line 32 (_def writer = new File("build.properties").newWriter("utf-8")_)it is writing to file build.properties 
Exception claims that permission is denied But i checked and in this file all the permissions are checked 
![issue#185v1](https://user-images.githubusercontent.com/43692789/76306938-d182c180-62ed-11ea-8c60-1c94199d5760.PNG)
Also when i built the project in my system it built successfully.

So maybe the issue is already fixed or at the time the error occured the file build.properties was simultaneously been open on another window causing an error.

So can we close this issue ?

**Comment by cyrille-artho** [comment] 2020-03-10 11:52
Yes, this works on other systems, and Windows has weird file locking so when you open a file in an editor, it usually gets locked.

**Closed by cyrille-artho** 2020-03-10 11:52 UTC
