### ISSUE TITLE
Orphan NativePeer method with Java 11.0.20.1

### ISSUE THREAD

**Issue by emileferreira** [javapathfinder/jpf-core#421] opened 2023-09-21 16:15 UTC
I'm using the latest version of JPF from the `master` branch, which is [documented](https://github.com/javapathfinder/jpf-core/wiki/System-requirements) as supporting Java SE 11, with Java 11.0.20.1. When invoking JPF, I'm greeted by the following warning.

```
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;
```

The output of `java --version` on my Arch Linux machine is as follows.

```
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1, mixed mode)
```

Is this something to be concerned about and, if so, which version of Java 11 is recommended?

**Comment by cyrille-artho** [comment] 2023-09-27 09:34
Thanks, this is indeed a bug. Our regression tests do not check whether unexpected warnings occur so we have not caught that.
The warning means that there is a declared native method that refers to a non-existent native method. In this case, I think the problem lies in `src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java`:

```
  public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) {
```

Simply changing the "mangled" return type to the mangled equivalent of `jdk.internal.misc.Unsafe` should fix this.

**Comment by anishlukk123** [comment] 2023-11-26 21:49
can i work on this

**Comment by adysinghh** [comment] 2024-01-09 09:25
@cyrille-artho hii, I had made some changes please review it.

**Comment by Nj221102** [comment] 2024-03-01 13:45
Is this issue still available ? can i work on this?  @cyrille-artho

**Comment by cyrille-artho** [comment] 2024-03-01 15:14
@adysinghh : You had nearly completed your patch back in early January except for some redundancy/formatting issues. I had left some comments about that on Jan 15. Are you planning on completing your PR?

**Comment by cyrille-artho** [comment] 2024-03-01 15:15
> Is this issue still available ? can i work on this? @cyrille-artho

Not sure, adysinghh had almost completed the fix but then has not done the final small step. I've added a comment above to notify him.

**Comment by adysinghh** [comment] 2024-03-01 16:13
@cyrille-artho Apologies for the delay, I've been caught up with exams. I'll address the redundancy and formatting issues pointed out in your comments before this weekend.

**Comment by Dashlet26** [comment] 2024-03-21 08:24
The warning message is related to presence of orphan NativePeer method . The warning suggests that there may be an issue with the compatibility of the Java version you are using (openjdk 11.0.20.1) with the JPF library. 
It is recommended to use a stable and well-tested version of Java 11 that is known to be compatible with the JPF library.

**Comment by cyrille-artho** [comment] 2024-03-21 08:32
The warning is simply because of a minor change we forgot to make in the Java 11 version. It is easy to fix, but finding out how to fix it is a good introduction to JPF's architecture for a first-time committer, so we leave this up for someone to fix.

**Comment by shreyasCs012** [comment] 2024-08-13 17:01
Hey @cyrille-artho, is this issue being taken care of?

**Comment by shreyasCs012** [comment] 2024-08-14 02:21
hey @cyrille-artho is someone working on it?

**Comment by cyrille-artho** [comment] 2024-08-14 06:34
It does not look like it, given that there has been no PR regarding this issue since March.

**Comment by shreyasCs012** [comment] 2024-08-14 06:53
### Is the issue here :

      There is a method in `src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java` called `getUnsafe__Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)`  that corresponds to native method which I think is "getUnsafe() " which is not declared as native, present in the class JPF_jdk_internal_misc_Unsafe which is in \src\peers\gov\nasa\jpf\vm

**Comment by shreyasCs012** [comment] 2024-08-14 07:22
### Is the issue here :
     There is a method in peer classes called `getUnsafe__Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)` that correspond to native method which i think is "getUnsafe() " present in the class JPF_jdk_internal_misc_Unsafe which is \src\peers\gov\nasa\jpf\vm

**Comment by shreyasCs012** [comment] 2024-08-14 07:24
Is the issue here :
   
   There is a method in peer classes called "getUnsafe__Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)" that corresponds to native method which I think is "getUnsafe() " present in the class JPF_jdk_internal_misc_Unsafe which is \src\peers\gov\nasa\jpf\vm

**Comment by cyrille-artho** [comment] 2024-08-14 07:30
See above: a change in the package name of the returned value results in the signature of the method no longer matching. If you update the "mangled" name of the native peer correctly, it will match again, and the warning by JPF will go away.

**Comment by shreyasCs012** [comment] 2024-08-14 08:47
i hava updated public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) to   public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)

**Comment by shreyasCs012** [comment] 2024-08-14 08:51
i hava updated ```public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)``` to public int ```getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef)```

**Comment by shreyasCs012** [comment] 2024-08-14 08:59
i have changed the "mangled" name to  ```public int getUnsafe____Ljdk_internal_misc_Unsafe_2 (MJIEnv env, int clsRef)``` from ```  public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) ```

**Comment by cyrille-artho** [comment] 2024-08-14 09:45
Does the warning that JPF emits upon start-up go away with that change? If so, please make a pull request with that change.

**Comment by shreyasCs012** [comment] 2024-08-14 10:33
there is an error which is popping up when I run the command gradle build 


  ``` PS C:\Users\shrey\jpf-core> gradle build

   > Task :compileClassesJava FAILED
   C:\Users\shrey\jpf-core\src\classes\modules\java.base\jdk\internal\misc\SharedSecrets.java:51: error: cannot access Unsafe
   private static final Unsafe unsafe = Unsafe.getUnsafe();
                       ^
   bad source file: C:\Users\shrey\jpf-core\src\classes\modules\java.base\jdk\internal\misc\Unsafe.java
    file does not contain class jdk.internal.misc.Unsafe
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
   1 error

FAILURE: Build failed with an exception.```

**Comment by cyrille-artho** [comment] 2024-08-14 10:53
What is the full set of changes you have made? Run `git diff` so we can see it. If you have not modified other files, then the code should compile.

**Comment by shreyasCs012** [comment] 2024-08-14 11:55
I ran ```git diff```  and saw I changed other files but I solved it and for now, I can see no warning : 
    ```   
     @MJI
   -  public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) {
  +  public int getUnsafe____Ljdk_internal_misc_Unsafe_2 (MJIEnv env, int clsRef){
     int objRef = env.getStaticReferenceField("jdk.internal.misc.Unsafe", "theUnsafe");
     return objRef;
   }
   ```
  ```
  PS C:\Users\shrey\jpf-core> gradle build 

 > Task :test

  ReporterResourcesTest > hashMustExist PASSED

ReporterResourcesTest > checkResources PASSED

TypeNameTest > testArrayCloning PASSED

BCDEncodedISBNTest > test10InvalidLength PASSED
```

**Comment by shreyasCs012** [comment] 2024-08-14 11:57
I ran git diff and saw I changed other files but I solved it and for now, I can see no warning : 

    ```  
   @MJI
   -  public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) {
  +  public int getUnsafe____Ljdk_internal_misc_Unsafe_2 (MJIEnv env, int clsRef){
     int objRef = env.getStaticReferenceField("jdk.internal.misc.Unsafe", "theUnsafe");
     return objRef;
   }
   ```
  the result of gradle build :

  ```
  PS C:\Users\shrey\jpf-core> gradle build 

 > Task :test

  ReporterResourcesTest > hashMustExist PASSED

ReporterResourcesTest > checkResources PASSED

TypeNameTest > testArrayCloning PASSED

BCDEncodedISBNTest > test10InvalidLength PASSED
```

**Comment by shreyasCs012** [comment] 2024-08-14 11:58
I ran ```git diff```  and saw I changed other files but I solved it and for now, I can see no warning : 

    ```  
   @MJI
   -  public int getUnsafe____Lsun_misc_Unsafe_2 (MJIEnv env, int clsRef) {
  +  public int getUnsafe____Ljdk_internal_misc_Unsafe_2 (MJIEnv env, int clsRef){
     int objRef = env.getStaticReferenceField("jdk.internal.misc.Unsafe", "theUnsafe");
     return objRef;
   }
   ```

**Comment by cyrille-artho** [comment] 2024-08-14 12:53
Great! Please make a pull request with that change. See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
If you have made the change locally on the clones repo, just fork the repo and copy the file that you have changed there.

**Comment by shreyasCs012** [comment] 2024-08-14 13:12
I have forked the repository and need to push it to my remote repo. After that, I will create a pull request. Is that okay?

**Comment by cyrille-artho** [comment] 2024-08-14 13:20
The existing PR shuffled around some other lines of code, which makes the change set larger than necessary and may make it difficult to integrate it with other branches in the future. Hence, I had asked for an update on that, but the update never happened.
You can make a new PR, and if the PR does not change other parts of the code, I can accept it and close the old PR.

**Comment by shreyasCs012** [comment] 2024-08-14 14:00
the new pr does not change the other part of the code and create that new pr and make sure that it does not change the other parts of the code beforee creating the new pr

**Comment by cyrille-artho** [comment] 2024-08-14 16:41
Great, thanks! I have merged your PR.

**Closed by cyrille-artho** 2024-08-14 16:41 UTC
Labels: bug, first issue
