### ISSUE TITLE
NoSuchMethodError: java.nio.StringCharBuffer.nextGetIndex

### ISSUE THREAD

**Issue by estebistec** [javapathfinder/jpf-core#343] opened 2023-02-21 22:16 UTC
Hello,

I'm running JPF on OpenJDK `1.8.0_362`, and am getting the referenced `NoSuchMethodError`. I also tried OpenJDK `11.0.18` and got the same result. I also reproduced with JPF from head of mainline.

The simplest reproduction inside of a JUnit that can otherwise run JPF in the IDE:

```java
        java.nio.charset.StandardCharsets.UTF_8.newEncoder().encode(java.nio.CharBuffer.wrap("heyo"));
```

The full stacktrace:

```
    [junit] gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
    [junit] java.lang.NoSuchMethodError: java.nio.StringCharBuffer.nextGetIndex()I
    [junit]     at java.nio.StringCharBuffer.get(StringCharBuffer.java:76)
    [junit]     at sun.nio.cs.UTF_8$Encoder.encodeBufferLoop(UTF_8.java:645)
    [junit]     at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:693)
    [junit]     at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
    [junit]     at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:802)
    [junit]     at REDACTED_MY_TEST_METHOD
 ```

**Comment by cyrille-artho** [comment] 2023-05-21 09:12
This is unexpected, as we don't have model classes for `java.nio.charset` or `java.nio.StringCharBuffer`. We now have students working for GSoC who can look at such problems, maybe they can find the root cause.

**Comment by arjuna2024** [comment] 2023-11-18 09:38
Hello @cyrille-artho I would like to contribute here, can you please let me know whether this issue resolved or not?

**Comment by cyrille-artho** [comment] 2023-11-18 14:56
No, it is not resolved yet, otherwise, we would have closed it.
Fixing the problem is simple, but creating an automated test that checks if it has been fixed is not. It would be great to have a test for this, but if it turns out to be too difficult to automate the test, just fixing the problem is fine, too.

**Comment by arjuna2024** [comment] 2023-11-18 17:52
Okay @cyrille-artho, Thanks for the information!

**Comment by cyrille-artho** [comment] 2024-02-26 14:36
The one-line example from the original submitter is likely the shortest example that shows the problem.
Look at our wiki page on how to write unit tests for JPF on how to encode this one-liner as a new unit test:
https://github.com/javapathfinder/jpf-core/wiki/Writing-JPF-tests 
After that, you have a new (failing) test. Fixing this test will be a bit harder than one line of code.
The test fails because we don't model all the internal functionality that the Java library uses.
First, you have to analyze where a fix would be suitable:
1. java.nio.charset.CharsetEncoder.encode
2. java.nio.StringCharBuffer.get
We currently don't have model classes for either of these classes.
How complex are these classes? How complex are the functions in question? Does it make sense to replace a whole class with a model class here? If the effort is too big, we may prioritize other functions instead. But if one of these two classes (and functions) are easy to model, it may be worth creating another model class.

**Comment by shreyasCs012** [comment] 2024-09-12 08:16
This test should check for the error   
    ```
@Test
    public void Test_Wrap() throws CharacterCodingException {
        if(verifyNoPropertyViolation()){
            java.nio.charset.StandardCharsets.UTF_8.newEncoder().encode(java.nio.CharBuffer.wrap("heyo"));
        }
    }
}
```

**Comment by shreyasCs012** [comment] 2024-09-12 08:18
This test should check for the error
```

 @Test
    public void Test_Wrap() throws CharacterCodingException {
        if(verifyNoPropertyViolation()){
            java.nio.charset.StandardCharsets.UTF_8.newEncoder().encode(java.nio.CharBuffer.wrap("heyo"));
        }
    }
```

**Comment by cyrille-artho** [comment] 2024-09-12 09:03
Thanks, with this test, I can see much better where the problem is:

`java.lang.NoSuchMethodError: java.nio.CharBuffer.arrayOffset()I`

This means that the model class in `src/classes/modules/java.base/java/nio/CharBuffer.java` does not support the method `arrayOffset` that would be needed here. Perhaps additional methods are also needed after `arrayOffset`. Adding `arrayOffset` is probably simple enough if it only involves returning the value of field `offset`, and if not, it is at least the first step you can try.

**Comment by shreyasCs012** [comment] 2024-09-12 09:56
I have added the method in the CharBuffer model class, it is showing the same `error was being thrown in the ByteBuffer model` class so` I went ahead and added the method there` too` but now it is throwing an error that suggests that the flip() method is missing in the ByteBuffer model class`

### After adding the arrayOffset() in ByteBuffer
```
====================================================== search started: 9/12/24, 3:20 PM

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at java.nio.charset.CharsetEncoder.encode(java/nio/charset/CharsetEncoder.java:815)
	at CharBufferTest.Test_Wrap(CharBufferTest.java:13)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(gov/nasa/jpf/util/test/TestJPF.java:648)
```

**Comment by cyrille-artho** [comment] 2024-09-13 07:24
Thanks; it is unfortunately often the case that when a test uses new functionality, several new methods are needed. The methods in Byte/CharBuffer can all be implemented as model classes. The JDK libraries (of the host JVM) sometimes use native methods for performance reasons, but the performance is not important in JPF.

**Comment by shreyasCs012** [comment] 2024-09-13 12:57
Is there any other way to fix it or should I keep on writing the method which are not being found?

**Comment by cyrille-artho** [comment] 2024-09-14 10:37
The approach of adding more and more methods to one or two model classes, one at a time, may be time-consuming but can work if one or two classes are relatively self-contained and their functionality is easy to model.
It's problematic when a lot of classes interact.
In this case, though, I don't see an alternative.

**Comment by shreyasCs012** [comment] 2024-09-14 14:11
I understand that the methods that are not found, such as the method mentioned above, seem complex. It looks like a peer method is missing, as I am unable to find the proper implementation for this peer method. Could you please show me where to find this implementation?

**Comment by shreyasCs012** [comment] 2024-09-15 01:56
The current method missing seems to be a native peer class but I could not find a class related to nio package even after creating a new class in the new directory also tried to add the file in the already initialized which is the src/peers/gov/nasa/jpf/vm but is still no working could please help

**Comment by cyrille-artho** [comment] 2024-09-16 06:06
We don't have native peers for the buffer classes in java.nio. In the host JVM, some methods are native for performance reasons, but in JPF, we need to observe the full effects of these methods on the buffer instances, so all buffer-related methods in JPF are regular methods.
If a method is declared as `native` in OpenJDK, you can still replace that method with a regular (non-native) peer in JPF.

**Comment by shreyasCs012** [comment] 2024-09-18 15:54
Thank you, I have implemented the `filp() `method in the ByteBuffer class and the error is fixed :

```

====================================================== system under test
CharBufferTest.runTestMethod()

====================================================== search started: 9/18/24, 9:22 PM

====================================================== results
no errors detected

====================================================== search finished: 9/18/24, 9:22 PM
> Task :test
CharBufferTest > Test_Wrap PASSED
```

**Closed** 2024-09-20 01:13 UTC
Labels: api support, first issue
