### ISSUE TITLE
NullPointerException in JVMAnnotationParser.setAnnotationFieldValue  

### ISSUE THREAD

**Issue by Novemser** [javapathfinder/jpf-core#179] opened 2019-03-20 04:07 UTC
I want to test a simple Spring Boot application: 
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SymbolicExecutionApplication {

	public static void main(String[] args) {
		SpringApplication.run(SymbolicExecutionApplication.class, args);
	}

}
```
but encountered this problem:
```bash
java.lang.NullPointerException
	at gov.nasa.jpf.jvm.JVMAnnotationParser.setAnnotationFieldValue(JVMAnnotationParser.java:140)
	at gov.nasa.jpf.jvm.ClassFile.setAnnotationFieldValue(ClassFile.java:799)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotationValue(ClassFile.java:1588)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotationValue(ClassFile.java:1595)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotationValues(ClassFile.java:1633)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotation(ClassFile.java:1622)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotationsAttr(ClassFile.java:1654)
	at gov.nasa.jpf.jvm.JVMAnnotationParser.setClassAttribute(JVMAnnotationParser.java:116)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:635)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1375)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:944)
	at gov.nasa.jpf.jvm.JVMAnnotationParser.parse(JVMAnnotationParser.java:64)
	at gov.nasa.jpf.vm.AnnotationInfo.<init>(AnnotationInfo.java:159)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createAnnotationInfo(JVMClassFileContainer.java:66)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedAnnotationInfo(ClassLoaderInfo.java:416)
	at gov.nasa.jpf.vm.ClassInfo.getResolvedAnnotationInfo(ClassInfo.java:432)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setAnnotation(JVMClassInfo.java:446)
	at gov.nasa.jpf.jvm.ClassFile.setAnnotation(ClassFile.java:697)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotation(ClassFile.java:1619)
	at gov.nasa.jpf.jvm.ClassFile.parseAnnotationsAttr(ClassFile.java:1654)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:93)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:635)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1375)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:944)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:713)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:58)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:33)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:353)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
	at gov.nasa.jpf.vm.VM.getMainClassInfo(VM.java:461)
	at gov.nasa.jpf.vm.VM.initializeMainThread(VM.java:565)
	at gov.nasa.jpf.vm.SingleProcessVM.initialize(SingleProcessVM.java:130)
	at gov.nasa.jpf.JPF.run(JPF.java:611)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
```
It seems `gov.nasa.jpf.jvm.JVMAnnotationParser#annotationStack` is null while creating new annotation for `org.springframework.boot.autoconfigure.SpringBootApplication`, any ideas or solutions? Thanks!

**Comment by cyrille-artho** [comment] 2019-03-25 13:44
I have not used annotations much with JPF. What happens if you write a simple example with your own annotation, and a class that uses it? Does that work? Perhaps the annotation is not in the classpath, and JPF crashes from that?

**Comment by Novemser** [comment] 2019-03-31 07:09
@cyrille-artho Thanks for your reply!
We wrote a simple annotation and no problem encountered. Also we have confirmed that the SpringBoot annotation is in the classpath and the problem still exists.

For now we would like to try to fix this problem, thanks for your help!

**Comment by cyrille-artho** [comment] 2019-03-31 09:51
Is the annotation in spring that crashes perhaps of a different type (e.g., using optional values) than the one you tried?
Is seems that this exception occurs if `setAnnotation` (in `JVMAnnotationParser.java`) is not called before `setAnnotationFieldValue` is called. The stack trace shows `setAnnotationFieldValue` (line 140) as the line that crashes, and the only place where the list `annotationStack` is initialized is `setAnnotation`. This looks like JPF may only support some types or use cases for annotations, and may need some fixing.

**Comment by cyrille-artho** [comment] 2023-08-03 11:21
I'll close this issue, as it is too difficult to reproduce (with the dependency on Spring Boot).

**Closed by cyrille-artho** 2023-08-03 11:21 UTC
Labels: bug
