### ISSUE TITLE
Getting a strange error from JPF

### ISSUE THREAD

**Issue by stevenrbrandt** [javapathfinder/jpf-core#323] opened 2022-04-05 18:33 UTC
I'm getting this error when running JPF. Any idea what it's telling me?
```
java.lang.ArrayIndexOutOfBoundsException: 1
        at gov.nasa.jpf.vm.NamedFields.setDoubleValue(NamedFields.java:164)
        at gov.nasa.jpf.vm.FunctionObjectFactory.setFuncObjFields(FunctionObjectFactory.java:60)
        at gov.nasa.jpf.vm.FunctionObjectFactory.getFunctionObject(FunctionObjectFactory.java:37)
        at gov.nasa.jpf.jvm.bytecode.INVOKEDYNAMIC.execute(INVOKEDYNAMIC.java:121)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
        at gov.nasa.jpf.search.Search.forward(Search.java:937)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at gov.nasa.jpf.tool.Run.call(Run.java:85)
        at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
```

**Comment by cyrille-artho** [comment] 2022-04-19 07:07
Hi,
This seems to be an internal error in JPF. Can you share a test case to reproduce this?

**Comment by stevenrbrandt** [comment] 2022-04-21 20:01
It may not be as small a test as you'd like, but here it is...
```
set -e

# Need java 1.8
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH="$JAVA_HOME/bin:$PATH"

# we want $jpf_root/bin/jpf to exist
export jpf_root=$PWD/jpf-core

if [ ! -d $jpf_root ]
then
    git clone https://github.com/javapathfinder/jpf-core.git $jpf_root
    pushd $jpf_root
    bash ./gradlew
    popd
fi

export experiment_root=$PWD
mkdir -p $PWD/account/source
mkdir -p $PWD/account/outputs

# We want our program called Main
cat > Main.java << EOF
import edu.lsu.cct.javalineer.sir.account.javalineer.Accounts;
import edu.lsu.cct.javalineer.MyPool;
public class Main {
    public static void main(String[] args) {
        System.out.println("Running code 1");
        MyPool mp = new MyPool(1);
        //mp.execute(()->{ System.out.println("Hello, world"); });
        Accounts.main(args);
        System.out.println("Done");
        System.exit(0);
    }
}
EOF

if [ ! -d javalineer ]
then
    git clone -b sir https://github.com/max-morris/javalineer.git
fi

javac -d account/source/ Main.java $(find javalineer -name \*.java|grep -v /test/)
cat > runJPF.sh << EOF
#!/bin/bash
RANDOM_RUNS=1 #number of random search; default is 1
TIMELIMIT=1 #let the clock tick to ensure each random search is unique

USAGE="Usage: \$0 comp_dir search_type [number_of_runs]\ncomp_dir: orig/fixed\rsearch_type: default/random\
    \nnumber_of_runs (optional): number of times JPF is invoked"

if [ "`echo "\t"`" == "\\t" ]
then
    ECHOE="echo -e"
else
    ECHOE="echo"
fi

if [ ! \${jpf_root} ]
then
    echo "jpf_root is unset in the shell"
    echo "please set jpf_root to point to your JPF installation"
    echo "see README for more information:"
    exit 2
fi

if [ ! \${experiment_root} ]
then
    echo "experiment_root is unset in the shell"
    echo "please set experiment_root to point to your experiment directory"
    echo "see README for more information:"
    exit 2
fi

if test \$# -lt 2
then
    \$ECHOE \$USAGE
    exit 0
fi

if test \$# -eq 3
then
    case \${3} in
        *[!0-9]* )
            echo "number of JPF runs is non-numeric" >&2
            \$ECHOE \$USAGE >&2
            exit 5
            ;;
    esac

    RANDOM_RUNS=\$3
fi

subject_dir=\${experiment_root}/account
cd \${subject_dir}/source

if test \$1 = "orig"
then
    if test \$2 = "default"
    then
        echo Invoking JPF
        \${jpf_root}/bin/jpf +classpath=\${subject_dir}/source \
            Main 1 1 12 2>&1 | tee \${subject_dir}/outputs/accountJPF.log
    else 
        if test \$2 = "random" 
        then
            echo Invoking JPF
             #if using expect to limit the amount of time spent on a search
             #set the TIMEOUT value below to the number of seconds
             #the search should run and uncomment
            TIMEOUT=3600
            X=0 #loop counter
            Z=\$RANDOM_RUNS #number of runs per test case
            while [ \$X -lt \$Z ]
            do
                seed=\$RANDOM
                echo "Seed: \$seed"
                  #Example of how to run JPF using expect to limit search time
                  #run JPF using expect - uncomment next four lines
		  #expect -c "set timeout \$TIMEOUT; set log_file \${subject_dir}/outputs/accountJPF\${seed}.log; spawn \
                  #\${jpf_root}/bin/jpf +classpath=\${subject_dir}/source \
                  #+cg.randomize_choices=path +cg.seed=\${seed} \
                  #Main 1 1 12 2>&1 |; log_file \${subject_dir}/outputs/accountJPF\${seed}.log; expect; log_file" \
                  #run JPF without expect
                  #comment out the following 4 lines if using expect above
                \${jpf_root}/bin/jpf +classpath=\${subject_dir}/source \
                    +cg.randomize_choices=FIXED_SEED +cg.seed=\$seed \
                    Main 1 1 12 2>&1 | \
                    tee \${subject_dir}/outputs/accountJPF\$seed.log 
                X=\$((X+1))
                  #Random run requires a clock tick to make sure a new random
                  #number is generated
	        sleep \$TIMELIMIT
            done
        fi
    fi
else
    echo orig is the only option currently available
fi
EOF
bash -x ./runJPF.sh orig random 1
```

**Comment by cyrille-artho** [comment] 2022-04-27 14:51
Thanks for the example. It is indeed a bit complex because it requires a library. Perhaps it's possible to provide a simplified example without that library, but of course creating that takes some time. I'll look into this when I have time.

**Comment by zavalyshyn** [comment] 2022-04-27 19:05
I'm getting the very same error message on my side. What would you recommend to do?
Is there any way to download a stable version that does not have this issue? I obtained my current version from this repo's master branch and I see no releases here. So what can we do?

**Comment by cyrille-artho** [comment] 2022-05-13 08:36
OK, thanks for confirming. I'll close this issue then.

**Comment by stevenrbrandt** [comment] 2022-05-13 15:16
Sorry, this issue should remain open. Unlike @zavalyshyn, I was using java 1.8 and got the error.

**Comment by stevenrbrandt** [comment] 2022-05-13 15:17
@cyrille-artho can we re-open it?

**Comment by Abhishekverma2002** [comment] 2023-04-04 09:55
Correct me if I am wrong but isn't this an array index out of bound error on those below listed lines.

**Comment by samvid25** [comment] 2023-08-01 23:47
I have another example where I ran into a similar error, in case it might help narrowing down the cause:
```java
public class TestArrays {
  public static void main(String[] args) {
    final int[] x = {1, 2, 3, 4, 5};
    Thread t1 = new Thread(() -> {
      int[] b = new int[x.length];
    });

    t1.start();

    try {
      t1.join();
    } catch (Exception e) {}
  }
}
```

The error: 
```
====================================================== search started: 8/1/23, 7:37 PM
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;
[SEVERE] JPF exception, terminating: not an array: java.lang.Thread
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFException: not an array: java.lang.Thread
        at gov.nasa.jpf.vm.ElementInfo.arrayLength(ElementInfo.java:1564)
        at gov.nasa.jpf.jvm.bytecode.ARRAYLENGTH.execute(ARRAYLENGTH.java:64)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1911)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1861)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1721)
        at gov.nasa.jpf.search.Search.forward(Search.java:579)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gov.nasa.jpf.tool.Run.call(Run.java:80)
        at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFException: not an array: java.lang.Thread
        at gov.nasa.jpf.vm.ElementInfo.arrayLength(ElementInfo.java:1564)
        at gov.nasa.jpf.jvm.bytecode.ARRAYLENGTH.execute(ARRAYLENGTH.java:64)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1911)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1861)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1721)
        at gov.nasa.jpf.search.Search.forward(Search.java:579)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gov.nasa.jpf.tool.Run.call(Run.java:80)
        at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
```

Some additional info from my experiments - the error doesn't occur if I replace `x.length` with a constant or an `int` variable. The error also doesn't occur when I don't use threads.

**Comment by samvid25** [comment] 2023-08-02 03:47
Great, thanks!

**Comment by cyrille-artho** [comment] 2023-08-03 11:20
OK, I'll close this issue, as a performance issue is not the same as a crash (if someone runs into this in a real example, we can open a new issue).

**Closed by cyrille-artho** 2023-08-03 11:20 UTC
Labels: bug
